In [1]:
library(tidyverse)
library(GGally)
library(car)
library(broom)

── Attaching core tidyverse packages ──────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: carData


Attaching package: ‘car’


The following object is masked from ‘package:dplyr’:

    recode


The following object is masked from ‘package:purrr’:

    some

In [2]:
players_data <- read_csv("players.csv") %>%
    mutate(pos = factor(sub(",.*", "", position), levels = c("GK", "DF", "MF", "FW"))) %>%
    filter(!is.na(goals)) %>%
    filter(position != "GK") %>%
    mutate(hours = minutes/60) %>%
    select(-position, -team_country, -minutes, -shots_on_target)

head(players_data)

Rows: 1248 Columns: 13
── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): team_country, position
dbl (11): age, minutes, goals, assists, cards_yellow, shots, shots_on_target...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  age goals assists cards_yellow shots fouls offsides interceptions tackles_won
1 23  0     0       0            0     0     1        0             0
2 26  1     0       0            3     1     0        0             1
3 24  0     0       0            2     0     0        1             0
4 34  0     0       0            0     0     0        4             3
5 23  0     0       1            9     3     1        3             5
6 23  0     0       0            0     0     0        0             0
  pos hours
1 FW  0.31666667
2 FW  4.18333333
3 MF  1.63333333
4 DF  6.00000000
5 MF  6.00000000
6 FW  0.01666667

In [3]:
players_data_lin_reg <- players_data %>%
    filter(goals > 0)

In [8]:
players_data_log_reg <- players_data %>%
    mutate(scored=if_else(goals > 0, 1, 0)) %>%
    select(-goals)

In [15]:
lin_reg_model = step(lm(log(goals) ~ ., data=players_data_lin_reg), direction = "backward")
log_reg_model = step(glm(scored ~ ., data=players_data_log_reg, family=binomial), direction = "backward")

Start:  AIC=-324.51
log(goals) ~ age + assists + cards_yellow + shots + fouls + offsides +
    interceptions + tackles_won + pos + hours

                Df Sum of Sq    RSS     AIC
- offsides       1    0.0029 25.547 -326.49
- age            1    0.0030 25.547 -326.49
- cards_yellow   1    0.0076 25.552 -326.46
- interceptions  1    0.0267 25.571 -326.32
- assists        1    0.0291 25.573 -326.31
- tackles_won    1    0.1887 25.733 -325.19
- pos            2    0.5362 26.080 -324.79
- fouls          1    0.2668 25.811 -324.65
<none>                       25.544 -324.51
- hours          1    0.2914 25.835 -324.48
- shots          1    5.1480 30.692 -293.65

Step:  AIC=-326.49
log(goals) ~ age + assists + cards_yellow + shots + fouls + interceptions +
    tackles_won + pos + hours

                Df Sum of Sq    RSS     AIC
- age            1    0.0033 25.550 -328.47
- cards_yellow   1    0.0068 25.554 -328.44
- interceptions  1    0.0290 25.576 -328.29
- assists        1    0.0318 25.579 -328.27
- tackles_won    1    0.2013 25.748 -327.08
- pos            2    0.5538 26.101 -326.65
- fouls          1    0.2672 25.814 -326.63
<none>                       25.547 -326.49
- hours          1    0.2940 25.841 -326.44
- shots          1    5.8392 31.386 -291.64

Step:  AIC=-328.47
log(goals) ~ assists + cards_yellow + shots + fouls + interceptions +
    tackles_won + pos + hours

                Df Sum of Sq    RSS     AIC
- cards_yellow   1    0.0080 25.558 -330.41
- interceptions  1    0.0308 25.581 -330.25
- assists        1    0.0313 25.582 -330.25
- tackles_won    1    0.2073 25.758 -329.02
- pos            2    0.5722 26.122 -328.50
- fouls          1    0.2850 25.835 -328.48
<none>                       25.550 -328.47
- hours          1    0.3122 25.863 -328.29
- shots          1    5.8401 31.390 -293.62

Step:  AIC=-330.41
log(goals) ~ assists + shots + fouls + interceptions + tackles_won +
    pos + hours

                Df Sum of Sq    RSS     AIC
- interceptions  1    0.0255 25.584 -332.23
- assists        1    0.0311 25.590 -332.19
- tackles_won    1    0.2199 25.778 -330.88
- fouls          1    0.2770 25.835 -330.48
- pos            2    0.5727 26.131 -330.44
<none>                       25.558 -330.41
- hours          1    0.3370 25.895 -330.06
- shots          1    5.8982 31.457 -295.24

Step:  AIC=-332.23
log(goals) ~ assists + shots + fouls + tackles_won + pos + hours

              Df Sum of Sq    RSS     AIC
- assists      1    0.0316 25.615 -334.01
- tackles_won  1    0.2520 25.836 -332.48
- fouls        1    0.2828 25.867 -332.26
<none>                     25.584 -332.23
- hours        1    0.3180 25.902 -332.02
- pos          2    0.6419 26.226 -331.80
- shots        1    7.1849 32.769 -289.93

Step:  AIC=-334.01
log(goals) ~ shots + fouls + tackles_won + pos + hours

              Df Sum of Sq    RSS     AIC
- tackles_won  1    0.2476 25.863 -334.29
<none>                     25.615 -334.01
- fouls        1    0.3171 25.933 -333.81
- hours        1    0.3668 25.982 -333.47
- pos          2    0.6947 26.310 -333.22
- shots        1    7.5888 33.204 -289.56

Step:  AIC=-334.29
log(goals) ~ shots + fouls + pos + hours

        Df Sum of Sq    RSS     AIC
- hours  1    0.1999 26.063 -334.91
<none>               25.863 -334.29
- fouls  1    0.4787 26.342 -333.01
- pos    2    1.1382 27.001 -330.58
- shots  1    7.9423 33.805 -288.35

Step:  AIC=-334.91
log(goals) ~ shots + fouls + pos

        Df Sum of Sq    RSS     AIC
- fouls  1    0.2881 26.351 -334.94
<none>               26.063 -334.91
- pos    2    0.9593 27.022 -332.44
- shots  1   16.3487 42.412 -249.75

Step:  AIC=-334.94
log(goals) ~ shots + pos

        Df Sum of Sq    RSS     AIC
<none>               26.351 -334.94
- pos    2    1.0297 27.381 -332.08
- shots  1   17.0010 43.352 -247.83
Start:  AIC=701.44
scored ~ age + assists + cards_yellow + shots + fouls + offsides +
    interceptions + tackles_won + pos + hours

                Df Deviance    AIC
- assists        1   677.45 699.45
- interceptions  1   677.47 699.47
- fouls          1   677.48 699.48
- offsides       1   678.54 700.54
- age            1   679.05 701.05
- hours          1   679.27 701.27
<none>               677.44 701.44
- pos            2   682.04 702.04
- tackles_won    1   680.22 702.22
- cards_yellow   1   680.31 702.31
- shots          1   751.21 773.21

Step:  AIC=699.45
scored ~ age + cards_yellow + shots + fouls + offsides + interceptions +
    tackles_won + pos + hours

                Df Deviance    AIC
- interceptions  1   677.49 697.49
- fouls          1   677.49 697.49
- offsides       1   678.55 698.55
- age            1   679.06 699.06
- hours          1   679.31 699.31
<none>               677.45 699.45
- pos            2   682.05 700.05
- tackles_won    1   680.22 700.22
- cards_yellow   1   680.39 700.39
- shots          1   752.16 772.16

Step:  AIC=697.49
scored ~ age + cards_yellow + shots + fouls + offsides + tackles_won +
    pos + hours

               Df Deviance    AIC
- fouls         1   677.53 695.53
- offsides      1   678.55 696.55
- age           1   679.09 697.09
<none>              677.49 697.49
- hours         1   679.98 697.98
- pos           2   682.07 698.07
- tackles_won   1   680.22 698.22
- cards_yellow  1   680.60 698.60
- shots         1   754.42 772.42

Step:  AIC=695.53
scored ~ age + cards_yellow + shots + offsides + tackles_won +
    pos + hours

               Df Deviance    AIC
- offsides      1   678.57 694.57
- age           1   679.10 695.10
<none>              677.53 695.53
- pos           2   682.07 696.07
- hours         1   680.12 696.12
- tackles_won   1   680.52 696.52
- cards_yellow  1   680.68 696.68
- shots         1   754.48 770.48

Step:  AIC=694.57
scored ~ age + cards_yellow + shots + tackles_won + pos + hours

               Df Deviance    AIC
- age           1   679.87 693.87
<none>              678.57 694.57
- cards_yellow  1   681.39 695.39
- hours         1   681.84 695.84
- pos           2   684.03 696.03
- tackles_won   1   682.05 696.05
- shots         1   763.74 777.74

Step:  AIC=693.87
scored ~ cards_yellow + shots + tackles_won + pos + hours

               Df Deviance    AIC
<none>              679.87 693.87
- cards_yellow  1   682.50 694.50
- hours         1   682.85 694.85
- tackles_won   1   683.12 695.12
- pos           2   685.50 695.50
- shots         1   766.42 778.42

In [16]:
lin_reg_model

Call:
lm(formula = log(goals) ~ shots + pos, data = players_data_lin_reg)

Coefficients:
(Intercept)        shots        posMF        posFW
  -0.095447     0.053393    -0.004833     0.162888

In [17]:
log_reg_model

Call:  glm(formula = scored ~ cards_yellow + shots + tackles_won + pos +
    hours, family = binomial, data = players_data_log_reg)

Coefficients:
 (Intercept)  cards_yellow         shots   tackles_won         posMF
     -3.3771        0.2991        0.3431       -0.0894        0.5374
       posFW         hours
      0.7325        0.1085

Degrees of Freedom: 976 Total (i.e. Null);  970 Residual
Null Deviance:	    930.6
Residual Deviance: 679.9 	AIC: 693.9

In [18]:
lin_reg_results <- 
   tidy(lin_reg_model, conf.int=0.95) %>% 
   mutate_if(is.numeric, round, 2)
lin_reg_results

  term        estimate std.error statistic p.value conf.low conf.high
1 (Intercept) -0.10    0.08      -1.27     0.21    -0.24    0.05
2 shots        0.05    0.01      10.63     0.00     0.04    0.06
3 posMF        0.00    0.09      -0.06     0.95    -0.17    0.16
4 posFW        0.16    0.09       1.74     0.08    -0.02    0.35

In [19]:
log_reg_results <- 
   tidy(log_reg_model, conf.int=0.95) %>% 
   mutate_if(is.numeric, round, 2)
log_reg_results

  term         estimate std.error statistic p.value conf.low conf.high
1 (Intercept)  -3.38    0.30      -11.38    0.00    -3.99    -2.82
2 cards_yellow  0.30    0.18        1.64    0.10    -0.06     0.65
3 shots         0.34    0.04        7.95    0.00     0.26     0.43
4 tackles_won  -0.09    0.05       -1.76    0.08    -0.19     0.01
5 posMF         0.54    0.28        1.95    0.05     0.00     1.09
6 posFW         0.73    0.33        2.25    0.02     0.10     1.38
7 hours         0.11    0.06        1.74    0.08    -0.01     0.23